---
title: C26111 |Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
caps.latest.revision: 10
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 22e2b3663c24d13ae92d1d8aa7a34a2dd513bba4
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 08/22/2018
ms.locfileid: "47548814"
---
# <a name="c26111"></a>C26111
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

このトピックの最新バージョンをご覧[C26111](https://docs.microsoft.com/visualstudio/code-quality/c26111)します。  
  
警告 C26111: 呼び出し元でロックを解放する失敗\<ロック > 関数を呼び出す前に\<func >。  
  
 注釈`_Requires_lock_not_held_`で関数が呼び出されたときに指定されたロックのロック数が 0 より大きいことはできませんが、前提条件が課せられます。 警告 C26111 別の関数を呼び出す前に、ロックの解除に失敗した関数が発行されます。  
  
## <a name="example"></a>例  
 次の例では、ため、警告 C26111 が生成されます、`_Requires_lock_not_held_`への呼び出しによって前提条件に違反して`DoNotLock`ロックされている範囲内で。  
  
```  
  
typedef struct _DATA   
{  
    CRITICAL_SECTION cs;  
    int d;  
} DATA;  
  
_Requires_lock_not_held_(p->cs)   
  
void DoNotLock(DATA* p)  
{  
    EnterCriticalSection(&p->cs);   
    p->d = 0;  
    LeaveCriticalSection(&p->cs);  
}  
  
void LockedFunction(DATA* p)   
{   
    EnterCriticalSection(&p->cs);   
    DoNotLock(p); // Warning C26111  
    LeaveCriticalSection(&p->cs);  
}  
  
```



