---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 78988ce7995e3ae5fde0a6391cc0cf7b46128362
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 10/16/2019
ms.locfileid: "72448307"
---
# <a name="c28198"></a>C28198
警告 C28198: 例外によりメモリがリークしている可能性があります

 この警告は、例外が発生した後に割り当てられたメモリが解放されていないことを示します。 パスの末尾にあるステートメントは、例外を発生させることができます。 後で解放するためにコピーを保存した可能性のある関数にメモリが渡されました。

 この警告は、warning [C28197](../code-quality/c28197.md)とよく似ています。 ここでは、警告[C28197](../code-quality/c28197.md)と共に使用することをお勧めする注釈も使用できます。

## <a name="example"></a>例
 次のコード例では、この警告が生成されます。

```
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 次のコード例では、この警告は生成されません。

```
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
