---
title: "C28198 |Microsoft ドキュメント"
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C28198
helpviewer_keywords: C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
caps.latest.revision: "3"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: a930019b1f7369f1d6035eef4f467d0fe17c6732
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/22/2017
---
# <a name="c28198"></a>C28198
警告 C28198: 例外によりメモリがリークしている可能性があります  
  
 この警告は、割り当てられたメモリを解放されていない例外が発生した後を示します。 パスの最後に、ステートメントは、例外を生成できます。 メモリは、後で解放されるコピーが保存した関数に渡されました。  
  
 この警告は警告によく似た[C28197](../code-quality/c28197.md)です。 警告で使用するために推奨される注釈[C28197](../code-quality/c28197.md)ここでも使用できます。  
  
## <a name="example"></a>例  
 次のコード例では、この警告が生成されます。  
  
```  
char *p1 = new char[10];  
char *p2 = new char[10];  
  
test(p1);   // does not save a copy of p  
  
delete[] p2;  
delete[] p1;  
```  
  
 次のコード例では、この警告は生成されません。  
  
```  
char *p1 = new char[10];  
char *p2 = NULL;  
  
test(p1);   // does not save a copy of p  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
```